FROM alpine:3.11

RUN apk add ca-certificates tzdata
WORKDIR /app

COPY zoneinfo.zip /app/zoneinfo.zip
ENV ZONEINFO /app/zoneinfo.zip

COPY ./build/service_notifications /app/service_notifications

ENTRYPOINT ["/app/service_notifications"]